version: '3.3'
services:

  mongo:
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    build:
      context: ./mongo
      dockerfile: Dockerfile
    ports:
    - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    links:
      - mongo
    ports:
      - 27070:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: f9miao
      ME_CONFIG_BASICAUTH_PASSWORD: f9miao
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo

  signup:
    container_name: signup
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 27080:27080
    environment:
      spring.mail.username:
      spring.mail.password:
      spring.data.mongodb.host:
